apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.prod.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: flow-api
  name: flow-api
spec:
  ports:
    - name: "8112"
      port: 8112
      targetPort: 8112
    - name: "8113"
      port: 8113
      targetPort: 8113
  selector:
    io.kompose.service: flow-api
