apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.prod.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: peerdb
  name: peerdb
spec:
  ports:
    - name: "9900"
      port: 9900
      targetPort: 9900
  selector:
    io.kompose.service: peerdb
