apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.prod.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: temporal-ui
  name: temporal-ui
spec:
  ports:
    - name: "8085"
      port: 8085
      targetPort: 8080
  selector:
    io.kompose.service: temporal-ui
